from .SpecImports import *
from toontown.toonbase import ToontownGlobals
LobbyParent = 10014
BoilerParent = 10030
PipeLeftParent = 10023
PipeRightParent = 10032
OilParent = 10034
ControlParent = 10037
DuctParent = 10036
CenterSiloBattleCellParent = 10064
CenterSiloParent = 20095
SigRoomParent = 20058
WestSiloParent = 20094
WestSiloBattleCellParent = 10047
EastSiloParent = 20096
EastSiloBattleCellParent = 10068
LavaFoyerParent = 7000
LobbyCell = 0
BoilerCell = 1
PipeLeftCell = 2
PipeRightCell = 3
OilCell = 4
ControlCell = 5
DuctCell = 6
CenterSiloCell = 7
SigRoomCell = 8
WestSiloCell = 9
EastSiloCell = 10
LavaFoyerCell = 11
BattleCells = {LobbyCell: {'parentEntId': LobbyParent,
             'pos': Point3(0, 0, 0)},
 BoilerCell: {'parentEntId': BoilerParent,
              'pos': Point3(0, 0, 0)},
 OilCell: {'parentEntId': OilParent,
           'pos': Point3(0, 0, 0)},
 ControlCell: {'parentEntId': ControlParent,
               'pos': Point3(0, 0, 0)},
 CenterSiloCell: {'parentEntId': CenterSiloBattleCellParent,
                  'pos': Point3(0, 0, 0)},
 PipeLeftCell: {'parentEntId': PipeLeftParent,
                'pos': Point3(0, 0, 0)},
 PipeRightCell: {'parentEntId': PipeRightParent,
                 'pos': Point3(0, 0, 0)},      
 DuctCell: {'parentEntId': DuctParent,
            'pos': Point3(0, 0, 0)},
 SigRoomCell: {'parentEntId': SigRoomParent,
               'pos': Point3(0, 0, 0)},
 WestSiloCell: {'parentEntId': WestSiloBattleCellParent,
                'pos': Point3(0, 0, 0)},
 EastSiloCell: {'parentEntId': EastSiloBattleCellParent,
                'pos': Point3(-20, -10, 0)},
 LavaFoyerCell: {'parentEntId': LavaFoyerParent,
            'pos': Point3(0, 0, 0)}}  
CogData = [{'parentEntId': LobbyParent, # Lobby
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20078,
  'skeleton': 0},
 {'parentEntId': LobbyParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20009,
  'skeleton': 0},
 {'parentEntId': LobbyParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20079,
  'skeleton': 0},
 {'parentEntId': BoilerParent, # Boiler Room
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': 0},
 {'parentEntId': BoilerParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': 0},
 {'parentEntId': BoilerParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 0},
 {'parentEntId': OilParent, # Oil Room
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': 0},
 {'parentEntId': OilParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': OilCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': OilParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': 0},
 {'parentEntId': OilParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': 0},
 {'parentEntId': ControlParent, # Gear Room
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 1},
 {'parentEntId': ControlParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 1},
 {'parentEntId': ControlParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20075,
  'skeleton': 1},
 {'parentEntId': CenterSiloParent, # Center Silo Control Room 
  'boss': 1, # Supervisor
  'level': ToontownGlobals.SellbotSteelFactorySupervisorLevel(),
  'battleCell': CenterSiloCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}, # For now until replaced with Foreman
 {'parentEntId': CenterSiloParent,
  'boss': 0, 
  'level': ToontownGlobals.SellbotSteelFactoryControlRoomMediumLevel(), 
  'battleCell': CenterSiloCell,
  'pos': Point3(-2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryControlRoomHigherLevel(),
  'battleCell': CenterSiloCell,
  'pos': Point3(2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryControlRoomMediumLevel(),
  'battleCell': CenterSiloCell,
  'pos': Point3(6, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': WestSiloParent, # West Silo
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloMediumLevel(),
  'battleCell': WestSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20097,
  'skeleton': 0},
 {'parentEntId': WestSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloMediumLevel(),
  'battleCell': WestSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20098,
  'skeleton': 0},
 {'parentEntId': WestSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloHigherLevel(),
  'battleCell': WestSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20099,
  'skeleton': 0},
 {'parentEntId': EastSiloParent, # East Silo
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloMediumLevel(),
  'battleCell': EastSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20100,
  'skeleton': 0},
 {'parentEntId': EastSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloMediumLevel(),
  'battleCell': EastSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20101,
  'skeleton': 0},
 {'parentEntId': EastSiloParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactorySiloHigherLevel(),
  'battleCell': EastSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20102,
  'skeleton': 0},
 {'parentEntId': PipeLeftParent, # Pipe Room (Left Side)
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20109,
  'skeleton': 1},
 {'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20110,
  'skeleton': 1},
 {'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeLeftCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20111,
  'skeleton': 1},
 {'parentEntId': PipeRightParent, # Pipe Room (Right Side)
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20106,
  'skeleton': 1},
 {'parentEntId': PipeRightParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20107,
  'skeleton': 1},
 {'parentEntId': PipeRightParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': PipeRightCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20108,
  'skeleton': 1},
 {'parentEntId': DuctParent, # Duct Room
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': 0},
 {'parentEntId': DuctParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': 0},
 {'parentEntId': DuctParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': DuctCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20068,
  'skeleton': 0},
 {'parentEntId': SigRoomParent, # Warehouse
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': SigRoomParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': SigRoomParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': SigRoomCell,
  'pos': Point3(5, 3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': SigRoomParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': SigRoomCell,
  'pos': Point3(5, 10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': LavaFoyerParent, # Lava Room Foyer
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LavaFoyerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': 0},
 {'parentEntId': LavaFoyerParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LavaFoyerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60134,
  'skeleton': 1},
 {'parentEntId': LavaFoyerParent,
  'boss': 0,
  'level': ToontownGlobals.SellbotSteelFactoryCogLevel(),
  'battleCell': LavaFoyerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': 0}]
ReserveCogData = []
